export const questionTypes = {
    GET_LIST: "GET_LIST",
    GET_CURRENT_QUESTION: "GET_CURRENT_QUESTION",
    ADD_QUESTION: "ADD_QUESTION",
    LOAD_MORE_LIST: "LOAD_MORE_LIST",
    DELETE_QUESTION: "DELETE_QUESTION"
}  